image: "node:12.13.1"

stages:
    - build
    - deploy
    - mirror

.github_template: &github_template |
    cd $REPO_DIR
    git add .
    git config user.name $GIT_USER_NAME       # the variable configured in Gitlab
    git config user.email "$GIT_USER_EMAIL"   # the variable configured in Gitlab
    git commit -m "$CI_COMMIT_MESSAGE"        # the variable configured in Gitlab
    git pull
    git push

before_script:
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_SERVER_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - cat ~/.ssh/id_rsa
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H 'github.com' >> ~/.ssh/known_hosts

build:
    stage: build
    tags:
        - docker
        - node12.13.1
    before_script:
        - yarn install --silent
    script:
        - yarn docs:build
    artifacts:
        paths:
            - docs/.vuepress/dist/

deploy:
    stage: deploy
    image: docker:git
    tags:
        - docker
        - git
    only:
        - master
    variables:
        REPO_DIR: "lytzeng.github.io"
    script:
        - git clone git@github.com:LYTzeng/lytzeng.github.io.git
        - rm -rf $($REPO_DIR/*)
        - cp -rf docs/.vuepress/dist/* $REPO_DIR
        - *github_template

mirror to github:
    stage: mirror
    image: docker:git
    tags:
        - docker
        - git
    variables:
        REPO_DIR: ".blog"
    script:
        - git clone git@github.com:LYTzeng/blog.git
        - mv blog $REPO_DIR
        - cp -rf * $REPO_DIR
        - cp -rf .gitlab-ci.yml $REPO_DIR
        - cp -rf .gitignore $REPO_DIR
        - *github_template